name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name: [windows, ubuntu, macos]
        buildtype: [Release, Debug]
        requirements: [source ./headers.sh]
        cmakeLists: [CMakeListsTxtBasic]
        include:
          - name: windows
            os: windows
            artifact: out/Build/Release/gmsv_ultralight_win64.dll
            tree: tree /f /a 
            requirements: start ./headers.bat
            cmakeLists: CMakeSettingsJson
          - name: ubuntu
            os: ubuntu
            artifact: out/libgmsv_ultralight_linux64.so
            tree: |
              sudo apt install tree
              tree -a .
          - name: macos
            os: macos
            artifact: out/Release/libgmsv_ultralight_linux64.dylib
            tree: |
              brew install tree
              tree -a
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    #- run: chmod +x ./headers.bat
    - run: ${{ matrix.requirements }}
    - uses: ilammy/msvc-dev-cmd@v1
    - name: 'CMake'
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: ${{ matrix.cmakeLists }}
        useVcpkgToolchainFile: true
        cmakeBuildType: ${{ matrix.buildtype }}
        buildDirectory: '${{ github.workspace }}/out'
    - name: tree
      run: ${{ matrix.tree }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.buildtype }}
        path: ${{ matrix.artifact }}
