name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: chmod +x ./headers.bat
    - run: start ./headers.bat
   # - run: set CGO_ENABLED=0
    - uses: ilammy/msvc-dev-cmd@v1
    - name: 'Run CMake with Visual Studio'
      uses: lukka/run-cmake@v2
      with:
        #cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        #cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        useVcpkgToolchainFile: true
        #cmakeAppendedArgs: '-G"Visual Studio 16 2019" -DCMAKE_CXX_COMPILER:FILEPATH=cl.exe' #  -DCMAKE_CXX_FLAGS=\"-std=c++11\"
        #cmakeListsOrSettingsJson: CMakeSettingsJson
        #cmakeSettingsJsonPath: '${{ github.workspace }}/CMakeSettings.json'
        #configurationRegexFilter: '${{ matrix.configuration }}'
        buildDirectory: '${{ github.workspace }}/out'
    - name: tree
      run: tree /f /a 
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Windows64
        path: out/Release/gmsv_ultralight_win64.dll
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: chmod +x ./headers.sh
    - run: source ./headers.sh
    - run: sudo apt install tree
    #- run: set CGO_ENABLED=0
    - name: 'Run CMake with Ninja'
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildDirectory: '${{ github.workspace }}/out/Release'
        cmakeAppendedArgs: '-GNinja ' # -DCMAKE_CXX_FLAGS=\"-std=c++11\"
    - name: tree
      run: tree -a .
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Linux64
        path: out/Release/libgmsv_ultralight_linux64.so
