name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name: [windows-msvc, ubuntu-g++, ubuntu-clang, macos-clang]
        buildtype: [Release, Debug]
        artifact: out/Release/libgmsv_ultralight_linux64.so
        requirements: source ./headers.sh
        include:
          - windows-msvc:
            os: windows
            cxx: cl.exe
            artifact: out/Build/Release/gmsv_ultralight_win64.dll
            tree: tree /f /a 
            requirements: start ./headers.bat
        include:
          - ubuntu-g++:
            os: ubuntu
            cxx: g++
            tree: |
              sudo apt install tree
              tree -a .
        include:
          - ubuntu-clang:
            os: ubuntu
            cxx: clang++
            tree: |
              sudo apt install tree
              tree -a .
        include:
          - macos-clang:
            os: macos
            cxx: clang++
            artifact: out/Release/libgmsv_ultralight_linux64.dylib
            tree: |
              brew install tree
              tree -a .

    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    #- run: chmod +x ./headers.bat
    - run: ${{ matrix.requirements }}
    - uses: ilammy/msvc-dev-cmd@v1
    - run: set CXX=${{ matrix.cxx }}
    - name: 'CMake'
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        useVcpkgToolchainFile: true
        cmakeBuildType: ${{ matrix.buildtype }}
        buildDirectory: '${{ github.workspace }}/out'
    - name: tree
      run: ${{ matrix.tree }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.artifact }}
