name: C/C++ CI

on:
  push:
    branches: [ tests ]
  pull_request:
    branches: [ tests ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: chmod +x ./headers.bat
    - run: start ./headers.bat
    - run: set CGO_ENABLED=0
    - uses: ilammy/msvc-dev-cmd@v1
    - run: choco install visualstudio2019buildtools
    - run: choco install visualstudio2019-workload-nativedesktop
    - name: 'Run CMake with Ninja'
      uses: lukka/run-cmake@v2
      with:
        #cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        useVcpkgToolchainFile: true
        cmakeAppendedArgs: '-GNinja -DCMAKE_CXX_COMPILER:FILEPATH=cl.exe' #  -DCMAKE_CXX_FLAGS=\"-std=c++11\"
        cmakeListsOrSettingsJson: CMakeSettingsJson
        cmakeSettingsJsonPath: '${{ github.workspace }}/CMakeSettings.json'
        configurationRegexFilter: '${{ matrix.configuration }}'
        buildDirectory: '${{ github.workspace }}/out/build'
    - name: tree
      run: tree /f /a 