name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        name: [windows, ubuntu, macos]
        buildtype: [Release, Debug]
        include:
          - name: windows
            os: windows
            tree: tree /f /a 
            requirements: start ./windows.bat
            cmakeLists: CMakeSettingsJson
          - name: ubuntu
            os: ubuntu
            artifact: out/libgmsv_ultralight_linux64.so
            tree: |
              sudo apt install tree
              tree -a .
            requirements: source ./linux.sh
            cmakeLists: CMakeListsTxtBasic
          - name: macos
            os: macos
            artifact: out/libgmsv_ultralight_linux64.dylib
            tree: |
              brew install tree
              tree -a
            requirements: source ./macos.sh
            cmakeLists: CMakeListsTxtBasic
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    #- run: chmod +x ./headers.bat
    - run: ${{ matrix.requirements }}
    - uses: ilammy/msvc-dev-cmd@v1
    - name: 'CMake'
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: ${{ matrix.cmakeLists }}
        useVcpkgToolchainFile: true
        cmakeBuildType: ${{ matrix.buildtype }}
        buildDirectory: '${{ github.workspace }}/out'
    - name: tree
      run: ${{ matrix.tree }}
    - name: set path
      if: "contains(matrix.os, 'windows')"
      run: set out/${{ matrix.buildtype }}/gmsv_ultralight_win64.dll
    - name: set path
      if: "!contains(matrix.os, 'windows')"
      run: export ${{ matrix.artifact }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.buildtype }}
        path: ${{ matrix.artifact }}
